#!/usr/bin/php
<?php

declare(strict_types=1);

use Muhsin\VK\Core\Database;
use Muhsin\VK\Core\Query;

require_once 'vendor/autoload.php';

$config = require 'config.php';
$db_config = $config['database'];

Database::init(
    [
        'host' => $db_config['host'],
        'port' => $db_config['port'],
        'dbname' => $db_config['database'],
        'charset' => $db_config['charset'],
    ],
    $db_config['username'],
    $db_config['password']
);

$command = $argv[1] ?? '';

switch ($command) {
    case 'migrate':
        /** @var Query[] $migrations */
        $migrations = [
            require 'migrations/create_users_table.php',
        ];

        foreach ($migrations as $migration) {
            $migration->execute();
        }

        echo 'Finished migrating!';
        break;
    case 'empty':
        $table = $argv[2] ?? false;

        if ($table === false) {
            echo 'Please provide table name!';
            break;
        }

        Database::getInstance()->query("TRUNCATE `$table`")->execute();
        echo 'Done!';
        break;
    default:
        echo 'Unknown command!';
        break;
}

echo PHP_EOL;
